== Requirements
:page-editUrl: https://github.com/davidsvejda/snow-ansible-docs

=== Ansible AWX

AWX provides a web-based user interface, REST API, and task engine built on top of Ansible. It is the upstream project for Tower, a commercial derivative of AWX.
See https://github.com/ansible/awx
==== Installation of AWX

Following docs at https://github.com/ansible/awx/blob/devel/INSTALL.md

Operating system CentOS 7

Install Ansible
---
yum install ansible
---

Install Docker

Install required packages
---
yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2
---

Use the following command to set up the stable repository
---
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
---

Install the latest version of Docker Engine - Community and containerd
---
yum install docker-ce docker-ce-cli containerd.io
---

Start Docker
---
systemctl start docker
---

Verify that Docker Engine - Community is installed correctly by running the hello-world image.
---
docker run hello-world
---

